import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'hi' | 'kk' | 'zh' | 'es' | 'th' | 'ru' | 'ja' | 'fr' | 'pt' | 'it' | 'ar' | 'tl' | 'vi' | 'id';

interface Translations {
  [key: string]: {
    [key: string]: string;
  };
}

const translations: Translations = {
  en: {
    title: 'Swift Energy Feedback Form',
    subtitle: 'Share your thoughts about our innovation',
    formTitle: 'Share Your Feedback',
    labelName: 'Your Name',
    placeholderName: 'Enter your name',
    labelAge: 'Your Age',
    placeholderAge: 'Enter your age',
    labelCountry: 'Your Country',
    placeholderCountry: 'Enter your country',
    labelTeam: 'Your FLL Team',
    placeholderTeam: 'Enter your FLL team name',
    labelThoughts: 'What are your overall thoughts about our innovation?',
    placeholderThoughts: 'Share your thoughts here...',
    labelFeelings: 'What do you feel about our explanation?',
    placeholderFeelings: 'Share your feelings here...',
    submitButton: 'Submit Feedback',
    submitting: 'Submitting...',
    viewFeedback: 'View Feedback',
    viewFeedbackShort: 'View',
    websiteButton: 'Our Website',
    websiteButtonShort: 'Website',
    allFeedback: 'All Feedback',
    feedbackDescription: 'View all submitted feedback from users around the world',
    tableHeaderName: 'Name',
    tableHeaderAge: 'Age',
    tableHeaderCountry: 'Country',
    tableHeaderTeam: 'FLL Team',
    tableHeaderThoughts: 'Thoughts',
    tableHeaderFeelings: 'Feelings',
    tableHeaderDate: 'Date',
    pinDialogTitle: 'Enter PIN',
    pinDialogDescription: 'Please enter the PIN to access the feedback section.',
    pinLabel: 'PIN',
    pinPlaceholder: 'Enter PIN',
    pinError: 'Incorrect PIN. Please try again.',
    pinSuccess: 'Access granted!',
    cancel: 'Cancel',
    verify: 'Verify',
    errorFillFields: 'Please fill in all fields',
    errorValidAge: 'Please enter a valid age',
    errorSubmit: 'Failed to submit feedback. Please try again.',
    successMessage: 'Thank you for your feedback!',
    errorLoadFeedback: 'Failed to load feedback. Please try again.',
    noFeedback: 'No feedback submitted yet. Be the first to share your thoughts!',
  },
  hi: {
    title: 'स्विफ्ट एनर्जी फीडबैक फॉर्म',
    subtitle: 'हमारे नवाचार के बारे में अपने विचार साझा करें',
    formTitle: 'अपनी प्रतिक्रिया साझा करें',
    labelName: 'आपका नाम',
    placeholderName: 'अपना नाम दर्ज करें',
    labelAge: 'आपकी उम्र',
    placeholderAge: 'अपनी उम्र दर्ज करें',
    labelCountry: 'आपका देश',
    placeholderCountry: 'अपना देश दर्ज करें',
    labelTeam: 'आपकी FLL टीम',
    placeholderTeam: 'अपनी FLL टीम का नाम दर्ज करें',
    labelThoughts: 'हमारे नवाचार के बारे में आपके समग्र विचार क्या हैं?',
    placeholderThoughts: 'अपने विचार यहां साझा करें...',
    labelFeelings: 'हमारी व्याख्या के बारे में आप क्या महसूस करते हैं?',
    placeholderFeelings: 'अपनी भावनाएं यहां साझा करें...',
    submitButton: 'फीडबैक सबमिट करें',
    submitting: 'सबमिट हो रहा है...',
    viewFeedback: 'फीडबैक देखें',
    viewFeedbackShort: 'देखें',
    websiteButton: 'हमारी वेबसाइट',
    websiteButtonShort: 'वेबसाइट',
    allFeedback: 'सभी फीडबैक',
    feedbackDescription: 'दुनिया भर के उपयोगकर्ताओं से सभी सबमिट की गई प्रतिक्रिया देखें',
    tableHeaderName: 'नाम',
    tableHeaderAge: 'उम्र',
    tableHeaderCountry: 'देश',
    tableHeaderTeam: 'FLL टीम',
    tableHeaderThoughts: 'विचार',
    tableHeaderFeelings: 'भावनाएं',
    tableHeaderDate: 'तारीख',
    pinDialogTitle: 'पिन दर्ज करें',
    pinDialogDescription: 'फीडबैक अनुभाग तक पहुंचने के लिए कृपया पिन दर्ज करें।',
    pinLabel: 'पिन',
    pinPlaceholder: 'पिन दर्ज करें',
    pinError: 'गलत पिन। कृपया पुनः प्रयास करें।',
    pinSuccess: 'पहुंच प्रदान की गई!',
    cancel: 'रद्द करें',
    verify: 'सत्यापित करें',
    errorFillFields: 'कृपया सभी फ़ील्ड भरें',
    errorValidAge: 'कृपया एक मान्य उम्र दर्ज करें',
    errorSubmit: 'फीडबैक सबमिट करने में विफल। कृपया पुनः प्रयास करें।',
    successMessage: 'आपकी प्रतिक्रिया के लिए धन्यवाद!',
    errorLoadFeedback: 'फीडबैक लोड करने में विफल। कृपया पुनः प्रयास करें।',
    noFeedback: 'अभी तक कोई फीडबैक सबमिट नहीं किया गया। अपने विचार साझा करने वाले पहले व्यक्ति बनें!',
  },
  kk: {
    title: 'Swift Energy пікір формасы',
    subtitle: 'Біздің инновация туралы ойларыңызбен бөлісіңіз',
    formTitle: 'Пікіріңізбен бөлісіңіз',
    labelName: 'Сіздің атыңыз',
    placeholderName: 'Атыңызды енгізіңіз',
    labelAge: 'Сіздің жасыңыз',
    placeholderAge: 'Жасыңызды енгізіңіз',
    labelCountry: 'Сіздің еліңіз',
    placeholderCountry: 'Еліңізді енгізіңіз',
    labelTeam: 'Сіздің FLL командаңыз',
    placeholderTeam: 'FLL командаңыздың атын енгізіңіз',
    labelThoughts: 'Біздің инновация туралы жалпы ойларыңыз қандай?',
    placeholderThoughts: 'Ойларыңызбен мұнда бөлісіңіз...',
    labelFeelings: 'Біздің түсіндірме туралы не ойлайсыз?',
    placeholderFeelings: 'Сезімдеріңізбен мұнда бөлісіңіз...',
    submitButton: 'Пікір жіберу',
    submitting: 'Жіберілуде...',
    viewFeedback: 'Пікірлерді көру',
    viewFeedbackShort: 'Көру',
    websiteButton: 'Біздің веб-сайт',
    websiteButtonShort: 'Сайт',
    allFeedback: 'Барлық пікірлер',
    feedbackDescription: 'Әлем бойынша пайдаланушылардан жіберілген барлық пікірлерді көру',
    tableHeaderName: 'Аты',
    tableHeaderAge: 'Жасы',
    tableHeaderCountry: 'Ел',
    tableHeaderTeam: 'FLL командасы',
    tableHeaderThoughts: 'Ойлар',
    tableHeaderFeelings: 'Сезімдер',
    tableHeaderDate: 'Күні',
    pinDialogTitle: 'PIN енгізіңіз',
    pinDialogDescription: 'Пікір бөліміне кіру үшін PIN енгізіңіз.',
    pinLabel: 'PIN',
    pinPlaceholder: 'PIN енгізіңіз',
    pinError: 'Қате PIN. Қайталап көріңіз.',
    pinSuccess: 'Қол жеткізу берілді!',
    cancel: 'Болдырмау',
    verify: 'Тексеру',
    errorFillFields: 'Барлық өрістерді толтырыңыз',
    errorValidAge: 'Жарамды жасты енгізіңіз',
    errorSubmit: 'Пікір жіберу сәтсіз аяқталды. Қайталап көріңіз.',
    successMessage: 'Пікіріңіз үшін рахмет!',
    errorLoadFeedback: 'Пікірлерді жүктеу сәтсіз аяқталды. Қайталап көріңіз.',
    noFeedback: 'Әзірге пікір жіберілмеген. Ойларыңызбен бөлісетін бірінші адам болыңыз!',
  },
  zh: {
    title: 'Swift Energy 反馈表',
    subtitle: '分享您对我们创新的想法',
    formTitle: '分享您的反馈',
    labelName: '您的姓名',
    placeholderName: '输入您的姓名',
    labelAge: '您的年龄',
    placeholderAge: '输入您的年龄',
    labelCountry: '您的国家',
    placeholderCountry: '输入您的国家',
    labelTeam: '您的 FLL 团队',
    placeholderTeam: '输入您的 FLL 团队名称',
    labelThoughts: '您对我们的创新有什么总体看法？',
    placeholderThoughts: '在此分享您的想法...',
    labelFeelings: '您对我们的解释有什么感受？',
    placeholderFeelings: '在此分享您的感受...',
    submitButton: '提交反馈',
    submitting: '提交中...',
    viewFeedback: '查看反馈',
    viewFeedbackShort: '查看',
    websiteButton: '我们的网站',
    websiteButtonShort: '网站',
    allFeedback: '所有反馈',
    feedbackDescription: '查看来自世界各地用户提交的所有反馈',
    tableHeaderName: '姓名',
    tableHeaderAge: '年龄',
    tableHeaderCountry: '国家',
    tableHeaderTeam: 'FLL 团队',
    tableHeaderThoughts: '想法',
    tableHeaderFeelings: '感受',
    tableHeaderDate: '日期',
    pinDialogTitle: '输入 PIN',
    pinDialogDescription: '请输入 PIN 以访问反馈部分。',
    pinLabel: 'PIN',
    pinPlaceholder: '输入 PIN',
    pinError: 'PIN 不正确。请重试。',
    pinSuccess: '访问已授予！',
    cancel: '取消',
    verify: '验证',
    errorFillFields: '请填写所有字段',
    errorValidAge: '请输入有效年龄',
    errorSubmit: '提交反馈失败。请重试。',
    successMessage: '感谢您的反馈！',
    errorLoadFeedback: '加载反馈失败。请重试。',
    noFeedback: '尚未提交反馈。成为第一个分享想法的人！',
  },
  es: {
    title: 'Formulario de comentarios de Swift Energy',
    subtitle: 'Comparte tus pensamientos sobre nuestra innovación',
    formTitle: 'Comparte tus comentarios',
    labelName: 'Tu nombre',
    placeholderName: 'Ingresa tu nombre',
    labelAge: 'Tu edad',
    placeholderAge: 'Ingresa tu edad',
    labelCountry: 'Tu país',
    placeholderCountry: 'Ingresa tu país',
    labelTeam: 'Tu equipo FLL',
    placeholderTeam: 'Ingresa el nombre de tu equipo FLL',
    labelThoughts: '¿Cuáles son tus pensamientos generales sobre nuestra innovación?',
    placeholderThoughts: 'Comparte tus pensamientos aquí...',
    labelFeelings: '¿Qué opinas de nuestra explicación?',
    placeholderFeelings: 'Comparte tus sentimientos aquí...',
    submitButton: 'Enviar comentarios',
    submitting: 'Enviando...',
    viewFeedback: 'Ver comentarios',
    viewFeedbackShort: 'Ver',
    websiteButton: 'Nuestro sitio web',
    websiteButtonShort: 'Sitio web',
    allFeedback: 'Todos los comentarios',
    feedbackDescription: 'Ver todos los comentarios enviados por usuarios de todo el mundo',
    tableHeaderName: 'Nombre',
    tableHeaderAge: 'Edad',
    tableHeaderCountry: 'País',
    tableHeaderTeam: 'Equipo FLL',
    tableHeaderThoughts: 'Pensamientos',
    tableHeaderFeelings: 'Sentimientos',
    tableHeaderDate: 'Fecha',
    pinDialogTitle: 'Ingresar PIN',
    pinDialogDescription: 'Por favor ingresa el PIN para acceder a la sección de comentarios.',
    pinLabel: 'PIN',
    pinPlaceholder: 'Ingresar PIN',
    pinError: 'PIN incorrecto. Por favor intenta de nuevo.',
    pinSuccess: '¡Acceso concedido!',
    cancel: 'Cancelar',
    verify: 'Verificar',
    errorFillFields: 'Por favor completa todos los campos',
    errorValidAge: 'Por favor ingresa una edad válida',
    errorSubmit: 'Error al enviar comentarios. Por favor intenta de nuevo.',
    successMessage: '¡Gracias por tus comentarios!',
    errorLoadFeedback: 'Error al cargar comentarios. Por favor intenta de nuevo.',
    noFeedback: 'Aún no se han enviado comentarios. ¡Sé el primero en compartir tus pensamientos!',
  },
  th: {
    title: 'แบบฟอร์มความคิดเห็น Swift Energy',
    subtitle: 'แบ่งปันความคิดของคุณเกี่ยวกับนวัตกรรมของเรา',
    formTitle: 'แบ่งปันความคิดเห็นของคุณ',
    labelName: 'ชื่อของคุณ',
    placeholderName: 'ใส่ชื่อของคุณ',
    labelAge: 'อายุของคุณ',
    placeholderAge: 'ใส่อายุของคุณ',
    labelCountry: 'ประเทศของคุณ',
    placeholderCountry: 'ใส่ประเทศของคุณ',
    labelTeam: 'ทีม FLL ของคุณ',
    placeholderTeam: 'ใส่ชื่อทีม FLL ของคุณ',
    labelThoughts: 'คุณคิดอย่างไรเกี่ยวกับนวัตกรรมของเราโดยรวม?',
    placeholderThoughts: 'แบ่งปันความคิดของคุณที่นี่...',
    labelFeelings: 'คุณรู้สึกอย่างไรเกี่ยวกับคำอธิบายของเรา?',
    placeholderFeelings: 'แบ่งปันความรู้สึกของคุณที่นี่...',
    submitButton: 'ส่งความคิดเห็น',
    submitting: 'กำลังส่ง...',
    viewFeedback: 'ดูความคิดเห็น',
    viewFeedbackShort: 'ดู',
    websiteButton: 'เว็บไซต์ของเรา',
    websiteButtonShort: 'เว็บไซต์',
    allFeedback: 'ความคิดเห็นทั้งหมด',
    feedbackDescription: 'ดูความคิดเห็นทั้งหมดที่ส่งมาจากผู้ใช้ทั่วโลก',
    tableHeaderName: 'ชื่อ',
    tableHeaderAge: 'อายุ',
    tableHeaderCountry: 'ประเทศ',
    tableHeaderTeam: 'ทีม FLL',
    tableHeaderThoughts: 'ความคิด',
    tableHeaderFeelings: 'ความรู้สึก',
    tableHeaderDate: 'วันที่',
    pinDialogTitle: 'ใส่ PIN',
    pinDialogDescription: 'กรุณาใส่ PIN เพื่อเข้าถึงส่วนความคิดเห็น',
    pinLabel: 'PIN',
    pinPlaceholder: 'ใส่ PIN',
    pinError: 'PIN ไม่ถูกต้อง กรุณาลองอีกครั้ง',
    pinSuccess: 'อนุญาตให้เข้าถึงแล้ว!',
    cancel: 'ยกเลิก',
    verify: 'ยืนยัน',
    errorFillFields: 'กรุณากรอกข้อมูลให้ครบทุกช่อง',
    errorValidAge: 'กรุณาใส่อายุที่ถูกต้อง',
    errorSubmit: 'ส่งความคิดเห็นไม่สำเร็จ กรุณาลองอีกครั้ง',
    successMessage: 'ขอบคุณสำหรับความคิดเห็นของคุณ!',
    errorLoadFeedback: 'โหลดความคิดเห็นไม่สำเร็จ กรุณาลองอีกครั้ง',
    noFeedback: 'ยังไม่มีความคิดเห็นที่ส่งมา เป็นคนแรกที่แบ่งปันความคิดของคุณ!',
  },
  ru: {
    title: 'Форма обратной связи Swift Energy',
    subtitle: 'Поделитесь своими мыслями о нашей инновации',
    formTitle: 'Поделитесь своим отзывом',
    labelName: 'Ваше имя',
    placeholderName: 'Введите ваше имя',
    labelAge: 'Ваш возраст',
    placeholderAge: 'Введите ваш возраст',
    labelCountry: 'Ваша страна',
    placeholderCountry: 'Введите вашу страну',
    labelTeam: 'Ваша команда FLL',
    placeholderTeam: 'Введите название вашей команды FLL',
    labelThoughts: 'Каковы ваши общие мысли о нашей инновации?',
    placeholderThoughts: 'Поделитесь своими мыслями здесь...',
    labelFeelings: 'Что вы думаете о нашем объяснении?',
    placeholderFeelings: 'Поделитесь своими чувствами здесь...',
    submitButton: 'Отправить отзыв',
    submitting: 'Отправка...',
    viewFeedback: 'Просмотреть отзывы',
    viewFeedbackShort: 'Просмотр',
    websiteButton: 'Наш веб-сайт',
    websiteButtonShort: 'Сайт',
    allFeedback: 'Все отзывы',
    feedbackDescription: 'Просмотреть все отзывы, отправленные пользователями со всего мира',
    tableHeaderName: 'Имя',
    tableHeaderAge: 'Возраст',
    tableHeaderCountry: 'Страна',
    tableHeaderTeam: 'Команда FLL',
    tableHeaderThoughts: 'Мысли',
    tableHeaderFeelings: 'Чувства',
    tableHeaderDate: 'Дата',
    pinDialogTitle: 'Введите PIN',
    pinDialogDescription: 'Пожалуйста, введите PIN для доступа к разделу отзывов.',
    pinLabel: 'PIN',
    pinPlaceholder: 'Введите PIN',
    pinError: 'Неверный PIN. Пожалуйста, попробуйте снова.',
    pinSuccess: 'Доступ предоставлен!',
    cancel: 'Отмена',
    verify: 'Проверить',
    errorFillFields: 'Пожалуйста, заполните все поля',
    errorValidAge: 'Пожалуйста, введите действительный возраст',
    errorSubmit: 'Не удалось отправить отзыв. Пожалуйста, попробуйте снова.',
    successMessage: 'Спасибо за ваш отзыв!',
    errorLoadFeedback: 'Не удалось загрузить отзывы. Пожалуйста, попробуйте снова.',
    noFeedback: 'Отзывов пока нет. Будьте первым, кто поделится своими мыслями!',
  },
  ja: {
    title: 'Swift Energy フィードバックフォーム',
    subtitle: '私たちのイノベーションについてのご意見をお聞かせください',
    formTitle: 'フィードバックを共有する',
    labelName: 'お名前',
    placeholderName: 'お名前を入力してください',
    labelAge: '年齢',
    placeholderAge: '年齢を入力してください',
    labelCountry: '国',
    placeholderCountry: '国を入力してください',
    labelTeam: 'FLLチーム',
    placeholderTeam: 'FLLチーム名を入力してください',
    labelThoughts: '私たちのイノベーションについての全体的な感想は？',
    placeholderThoughts: 'ご意見をここに共有してください...',
    labelFeelings: '私たちの説明についてどう思いますか？',
    placeholderFeelings: 'ご感想をここに共有してください...',
    submitButton: 'フィードバックを送信',
    submitting: '送信中...',
    viewFeedback: 'フィードバックを表示',
    viewFeedbackShort: '表示',
    websiteButton: '私たちのウェブサイト',
    websiteButtonShort: 'サイト',
    allFeedback: 'すべてのフィードバック',
    feedbackDescription: '世界中のユーザーから送信されたすべてのフィードバックを表示',
    tableHeaderName: '名前',
    tableHeaderAge: '年齢',
    tableHeaderCountry: '国',
    tableHeaderTeam: 'FLLチーム',
    tableHeaderThoughts: '意見',
    tableHeaderFeelings: '感想',
    tableHeaderDate: '日付',
    pinDialogTitle: 'PINを入力',
    pinDialogDescription: 'フィードバックセクションにアクセスするにはPINを入力してください。',
    pinLabel: 'PIN',
    pinPlaceholder: 'PINを入力',
    pinError: 'PINが正しくありません。もう一度お試しください。',
    pinSuccess: 'アクセスが許可されました！',
    cancel: 'キャンセル',
    verify: '確認',
    errorFillFields: 'すべてのフィールドに入力してください',
    errorValidAge: '有効な年齢を入力してください',
    errorSubmit: 'フィードバックの送信に失敗しました。もう一度お試しください。',
    successMessage: 'フィードバックをありがとうございます！',
    errorLoadFeedback: 'フィードバックの読み込みに失敗しました。もう一度お試しください。',
    noFeedback: 'まだフィードバックが送信されていません。最初にご意見を共有してください！',
  },
  fr: {
    title: 'Formulaire de commentaires Swift Energy',
    subtitle: 'Partagez vos réflexions sur notre innovation',
    formTitle: 'Partagez vos commentaires',
    labelName: 'Votre nom',
    placeholderName: 'Entrez votre nom',
    labelAge: 'Votre âge',
    placeholderAge: 'Entrez votre âge',
    labelCountry: 'Votre pays',
    placeholderCountry: 'Entrez votre pays',
    labelTeam: 'Votre équipe FLL',
    placeholderTeam: 'Entrez le nom de votre équipe FLL',
    labelThoughts: 'Quelles sont vos réflexions générales sur notre innovation ?',
    placeholderThoughts: 'Partagez vos réflexions ici...',
    labelFeelings: 'Que pensez-vous de notre explication ?',
    placeholderFeelings: 'Partagez vos sentiments ici...',
    submitButton: 'Soumettre les commentaires',
    submitting: 'Envoi en cours...',
    viewFeedback: 'Voir les commentaires',
    viewFeedbackShort: 'Voir',
    websiteButton: 'Notre site web',
    websiteButtonShort: 'Site web',
    allFeedback: 'Tous les commentaires',
    feedbackDescription: 'Voir tous les commentaires soumis par les utilisateurs du monde entier',
    tableHeaderName: 'Nom',
    tableHeaderAge: 'Âge',
    tableHeaderCountry: 'Pays',
    tableHeaderTeam: 'Équipe FLL',
    tableHeaderThoughts: 'Réflexions',
    tableHeaderFeelings: 'Sentiments',
    tableHeaderDate: 'Date',
    pinDialogTitle: 'Entrer le PIN',
    pinDialogDescription: 'Veuillez entrer le PIN pour accéder à la section des commentaires.',
    pinLabel: 'PIN',
    pinPlaceholder: 'Entrer le PIN',
    pinError: 'PIN incorrect. Veuillez réessayer.',
    pinSuccess: 'Accès accordé !',
    cancel: 'Annuler',
    verify: 'Vérifier',
    errorFillFields: 'Veuillez remplir tous les champs',
    errorValidAge: 'Veuillez entrer un âge valide',
    errorSubmit: 'Échec de la soumission des commentaires. Veuillez réessayer.',
    successMessage: 'Merci pour vos commentaires !',
    errorLoadFeedback: 'Échec du chargement des commentaires. Veuillez réessayer.',
    noFeedback: 'Aucun commentaire soumis pour le moment. Soyez le premier à partager vos réflexions !',
  },
  pt: {
    title: 'Formulário de Feedback Swift Energy',
    subtitle: 'Compartilhe seus pensamentos sobre nossa inovação',
    formTitle: 'Compartilhe seu Feedback',
    labelName: 'Seu Nome',
    placeholderName: 'Digite seu nome',
    labelAge: 'Sua Idade',
    placeholderAge: 'Digite sua idade',
    labelCountry: 'Seu País',
    placeholderCountry: 'Digite seu país',
    labelTeam: 'Sua Equipe FLL',
    placeholderTeam: 'Digite o nome da sua equipe FLL',
    labelThoughts: 'Quais são seus pensamentos gerais sobre nossa inovação?',
    placeholderThoughts: 'Compartilhe seus pensamentos aqui...',
    labelFeelings: 'O que você acha da nossa explicação?',
    placeholderFeelings: 'Compartilhe seus sentimentos aqui...',
    submitButton: 'Enviar Feedback',
    submitting: 'Enviando...',
    viewFeedback: 'Ver Feedback',
    viewFeedbackShort: 'Ver',
    websiteButton: 'Nosso site',
    websiteButtonShort: 'Site',
    allFeedback: 'Todos os Feedbacks',
    feedbackDescription: 'Ver todos os feedbacks enviados por usuários de todo o mundo',
    tableHeaderName: 'Nome',
    tableHeaderAge: 'Idade',
    tableHeaderCountry: 'País',
    tableHeaderTeam: 'Equipe FLL',
    tableHeaderThoughts: 'Pensamentos',
    tableHeaderFeelings: 'Sentimentos',
    tableHeaderDate: 'Data',
    pinDialogTitle: 'Digite o PIN',
    pinDialogDescription: 'Por favor, digite o PIN para acessar a seção de feedback.',
    pinLabel: 'PIN',
    pinPlaceholder: 'Digite o PIN',
    pinError: 'PIN incorreto. Por favor, tente novamente.',
    pinSuccess: 'Acesso concedido!',
    cancel: 'Cancelar',
    verify: 'Verificar',
    errorFillFields: 'Por favor, preencha todos os campos',
    errorValidAge: 'Por favor, insira uma idade válida',
    errorSubmit: 'Falha ao enviar feedback. Por favor, tente novamente.',
    successMessage: 'Obrigado pelo seu feedback!',
    errorLoadFeedback: 'Falha ao carregar feedback. Por favor, tente novamente.',
    noFeedback: 'Nenhum feedback enviado ainda. Seja o primeiro a compartilhar seus pensamentos!',
  },
  it: {
    title: 'Modulo di Feedback Swift Energy',
    subtitle: 'Condividi i tuoi pensieri sulla nostra innovazione',
    formTitle: 'Condividi il tuo Feedback',
    labelName: 'Il tuo Nome',
    placeholderName: 'Inserisci il tuo nome',
    labelAge: 'La tua Età',
    placeholderAge: 'Inserisci la tua età',
    labelCountry: 'Il tuo Paese',
    placeholderCountry: 'Inserisci il tuo paese',
    labelTeam: 'Il tuo Team FLL',
    placeholderTeam: 'Inserisci il nome del tuo team FLL',
    labelThoughts: 'Quali sono i tuoi pensieri generali sulla nostra innovazione?',
    placeholderThoughts: 'Condividi i tuoi pensieri qui...',
    labelFeelings: 'Cosa pensi della nostra spiegazione?',
    placeholderFeelings: 'Condividi i tuoi sentimenti qui...',
    submitButton: 'Invia Feedback',
    submitting: 'Invio in corso...',
    viewFeedback: 'Visualizza Feedback',
    viewFeedbackShort: 'Visualizza',
    websiteButton: 'Il nostro sito web',
    websiteButtonShort: 'Sito web',
    allFeedback: 'Tutti i Feedback',
    feedbackDescription: 'Visualizza tutti i feedback inviati dagli utenti di tutto il mondo',
    tableHeaderName: 'Nome',
    tableHeaderAge: 'Età',
    tableHeaderCountry: 'Paese',
    tableHeaderTeam: 'Team FLL',
    tableHeaderThoughts: 'Pensieri',
    tableHeaderFeelings: 'Sentimenti',
    tableHeaderDate: 'Data',
    pinDialogTitle: 'Inserisci PIN',
    pinDialogDescription: 'Inserisci il PIN per accedere alla sezione feedback.',
    pinLabel: 'PIN',
    pinPlaceholder: 'Inserisci PIN',
    pinError: 'PIN errato. Riprova.',
    pinSuccess: 'Accesso consentito!',
    cancel: 'Annulla',
    verify: 'Verifica',
    errorFillFields: 'Compila tutti i campi',
    errorValidAge: 'Inserisci un\'età valida',
    errorSubmit: 'Invio feedback fallito. Riprova.',
    successMessage: 'Grazie per il tuo feedback!',
    errorLoadFeedback: 'Caricamento feedback fallito. Riprova.',
    noFeedback: 'Nessun feedback inviato ancora. Sii il primo a condividere i tuoi pensieri!',
  },
  ar: {
    title: 'نموذج ملاحظات Swift Energy',
    subtitle: 'شارك أفكارك حول ابتكارنا',
    formTitle: 'شارك ملاحظاتك',
    labelName: 'اسمك',
    placeholderName: 'أدخل اسمك',
    labelAge: 'عمرك',
    placeholderAge: 'أدخل عمرك',
    labelCountry: 'بلدك',
    placeholderCountry: 'أدخل بلدك',
    labelTeam: 'فريق FLL الخاص بك',
    placeholderTeam: 'أدخل اسم فريق FLL الخاص بك',
    labelThoughts: 'ما هي أفكارك العامة حول ابتكارنا؟',
    placeholderThoughts: 'شارك أفكارك هنا...',
    labelFeelings: 'ما رأيك في شرحنا؟',
    placeholderFeelings: 'شارك مشاعرك هنا...',
    submitButton: 'إرسال الملاحظات',
    submitting: 'جاري الإرسال...',
    viewFeedback: 'عرض الملاحظات',
    viewFeedbackShort: 'عرض',
    websiteButton: 'موقعنا الإلكتروني',
    websiteButtonShort: 'الموقع',
    allFeedback: 'جميع الملاحظات',
    feedbackDescription: 'عرض جميع الملاحظات المقدمة من المستخدمين حول العالم',
    tableHeaderName: 'الاسم',
    tableHeaderAge: 'العمر',
    tableHeaderCountry: 'البلد',
    tableHeaderTeam: 'فريق FLL',
    tableHeaderThoughts: 'الأفكار',
    tableHeaderFeelings: 'المشاعر',
    tableHeaderDate: 'التاريخ',
    pinDialogTitle: 'أدخل الرقم السري',
    pinDialogDescription: 'يرجى إدخال الرقم السري للوصول إلى قسم الملاحظات.',
    pinLabel: 'الرقم السري',
    pinPlaceholder: 'أدخل الرقم السري',
    pinError: 'رقم سري غير صحيح. يرجى المحاولة مرة أخرى.',
    pinSuccess: 'تم منح الوصول!',
    cancel: 'إلغاء',
    verify: 'تحقق',
    errorFillFields: 'يرجى ملء جميع الحقول',
    errorValidAge: 'يرجى إدخال عمر صالح',
    errorSubmit: 'فشل إرسال الملاحظات. يرجى المحاولة مرة أخرى.',
    successMessage: 'شكراً لملاحظاتك!',
    errorLoadFeedback: 'فشل تحميل الملاحظات. يرجى المحاولة مرة أخرى.',
    noFeedback: 'لم يتم إرسال أي ملاحظات بعد. كن أول من يشارك أفكاره!',
  },
  tl: {
    title: 'Swift Energy Feedback Form',
    subtitle: 'Ibahagi ang iyong mga saloobin tungkol sa aming innovation',
    formTitle: 'Ibahagi ang Iyong Feedback',
    labelName: 'Iyong Pangalan',
    placeholderName: 'Ilagay ang iyong pangalan',
    labelAge: 'Iyong Edad',
    placeholderAge: 'Ilagay ang iyong edad',
    labelCountry: 'Iyong Bansa',
    placeholderCountry: 'Ilagay ang iyong bansa',
    labelTeam: 'Iyong FLL Team',
    placeholderTeam: 'Ilagay ang pangalan ng iyong FLL team',
    labelThoughts: 'Ano ang iyong pangkalahatang saloobin tungkol sa aming innovation?',
    placeholderThoughts: 'Ibahagi ang iyong mga saloobin dito...',
    labelFeelings: 'Ano ang iyong nararamdaman tungkol sa aming paliwanag?',
    placeholderFeelings: 'Ibahagi ang iyong mga damdamin dito...',
    submitButton: 'Isumite ang Feedback',
    submitting: 'Isinusumite...',
    viewFeedback: 'Tingnan ang Feedback',
    viewFeedbackShort: 'Tingnan',
    websiteButton: 'Aming Website',
    websiteButtonShort: 'Website',
    allFeedback: 'Lahat ng Feedback',
    feedbackDescription: 'Tingnan ang lahat ng naisumiteng feedback mula sa mga user sa buong mundo',
    tableHeaderName: 'Pangalan',
    tableHeaderAge: 'Edad',
    tableHeaderCountry: 'Bansa',
    tableHeaderTeam: 'FLL Team',
    tableHeaderThoughts: 'Mga Saloobin',
    tableHeaderFeelings: 'Mga Damdamin',
    tableHeaderDate: 'Petsa',
    pinDialogTitle: 'Ilagay ang PIN',
    pinDialogDescription: 'Pakiusap ilagay ang PIN upang ma-access ang feedback section.',
    pinLabel: 'PIN',
    pinPlaceholder: 'Ilagay ang PIN',
    pinError: 'Maling PIN. Pakisubukan muli.',
    pinSuccess: 'Access granted!',
    cancel: 'Kanselahin',
    verify: 'I-verify',
    errorFillFields: 'Pakipunan ang lahat ng fields',
    errorValidAge: 'Pakiusap maglagay ng wastong edad',
    errorSubmit: 'Nabigo ang pagsusumite ng feedback. Pakisubukan muli.',
    successMessage: 'Salamat sa iyong feedback!',
    errorLoadFeedback: 'Nabigo ang pag-load ng feedback. Pakisubukan muli.',
    noFeedback: 'Walang naisumiteng feedback pa. Maging una na magbahagi ng iyong mga saloobin!',
  },
  vi: {
    title: 'Biểu mẫu Phản hồi Swift Energy',
    subtitle: 'Chia sẻ suy nghĩ của bạn về sự đổi mới của chúng tôi',
    formTitle: 'Chia sẻ Phản hồi của Bạn',
    labelName: 'Tên của Bạn',
    placeholderName: 'Nhập tên của bạn',
    labelAge: 'Tuổi của Bạn',
    placeholderAge: 'Nhập tuổi của bạn',
    labelCountry: 'Quốc gia của Bạn',
    placeholderCountry: 'Nhập quốc gia của bạn',
    labelTeam: 'Đội FLL của Bạn',
    placeholderTeam: 'Nhập tên đội FLL của bạn',
    labelThoughts: 'Suy nghĩ tổng thể của bạn về sự đổi mới của chúng tôi là gì?',
    placeholderThoughts: 'Chia sẻ suy nghĩ của bạn tại đây...',
    labelFeelings: 'Bạn cảm thấy thế nào về lời giải thích của chúng tôi?',
    placeholderFeelings: 'Chia sẻ cảm xúc của bạn tại đây...',
    submitButton: 'Gửi Phản hồi',
    submitting: 'Đang gửi...',
    viewFeedback: 'Xem Phản hồi',
    viewFeedbackShort: 'Xem',
    websiteButton: 'Trang web của chúng tôi',
    websiteButtonShort: 'Trang web',
    allFeedback: 'Tất cả Phản hồi',
    feedbackDescription: 'Xem tất cả phản hồi được gửi từ người dùng trên toàn thế giới',
    tableHeaderName: 'Tên',
    tableHeaderAge: 'Tuổi',
    tableHeaderCountry: 'Quốc gia',
    tableHeaderTeam: 'Đội FLL',
    tableHeaderThoughts: 'Suy nghĩ',
    tableHeaderFeelings: 'Cảm xúc',
    tableHeaderDate: 'Ngày',
    pinDialogTitle: 'Nhập PIN',
    pinDialogDescription: 'Vui lòng nhập PIN để truy cập phần phản hồi.',
    pinLabel: 'PIN',
    pinPlaceholder: 'Nhập PIN',
    pinError: 'PIN không chính xác. Vui lòng thử lại.',
    pinSuccess: 'Đã cấp quyền truy cập!',
    cancel: 'Hủy',
    verify: 'Xác minh',
    errorFillFields: 'Vui lòng điền vào tất cả các trường',
    errorValidAge: 'Vui lòng nhập tuổi hợp lệ',
    errorSubmit: 'Gửi phản hồi thất bại. Vui lòng thử lại.',
    successMessage: 'Cảm ơn phản hồi của bạn!',
    errorLoadFeedback: 'Tải phản hồi thất bại. Vui lòng thử lại.',
    noFeedback: 'Chưa có phản hồi nào được gửi. Hãy là người đầu tiên chia sẻ suy nghĩ của bạn!',
  },
  id: {
    title: 'Formulir Umpan Balik Swift Energy',
    subtitle: 'Bagikan pemikiran Anda tentang inovasi kami',
    formTitle: 'Bagikan Umpan Balik Anda',
    labelName: 'Nama Anda',
    placeholderName: 'Masukkan nama Anda',
    labelAge: 'Usia Anda',
    placeholderAge: 'Masukkan usia Anda',
    labelCountry: 'Negara Anda',
    placeholderCountry: 'Masukkan negara Anda',
    labelTeam: 'Tim FLL Anda',
    placeholderTeam: 'Masukkan nama tim FLL Anda',
    labelThoughts: 'Apa pemikiran Anda secara keseluruhan tentang inovasi kami?',
    placeholderThoughts: 'Bagikan pemikiran Anda di sini...',
    labelFeelings: 'Apa yang Anda rasakan tentang penjelasan kami?',
    placeholderFeelings: 'Bagikan perasaan Anda di sini...',
    submitButton: 'Kirim Umpan Balik',
    submitting: 'Mengirim...',
    viewFeedback: 'Lihat Umpan Balik',
    viewFeedbackShort: 'Lihat',
    websiteButton: 'Situs Web Kami',
    websiteButtonShort: 'Situs Web',
    allFeedback: 'Semua Umpan Balik',
    feedbackDescription: 'Lihat semua umpan balik yang dikirimkan dari pengguna di seluruh dunia',
    tableHeaderName: 'Nama',
    tableHeaderAge: 'Usia',
    tableHeaderCountry: 'Negara',
    tableHeaderTeam: 'Tim FLL',
    tableHeaderThoughts: 'Pemikiran',
    tableHeaderFeelings: 'Perasaan',
    tableHeaderDate: 'Tanggal',
    pinDialogTitle: 'Masukkan PIN',
    pinDialogDescription: 'Silakan masukkan PIN untuk mengakses bagian umpan balik.',
    pinLabel: 'PIN',
    pinPlaceholder: 'Masukkan PIN',
    pinError: 'PIN salah. Silakan coba lagi.',
    pinSuccess: 'Akses diberikan!',
    cancel: 'Batal',
    verify: 'Verifikasi',
    errorFillFields: 'Harap isi semua kolom',
    errorValidAge: 'Harap masukkan usia yang valid',
    errorSubmit: 'Gagal mengirim umpan balik. Silakan coba lagi.',
    successMessage: 'Terima kasih atas umpan balik Anda!',
    errorLoadFeedback: 'Gagal memuat umpan balik. Silakan coba lagi.',
    noFeedback: 'Belum ada umpan balik yang dikirimkan. Jadilah yang pertama untuk berbagi pemikiran Anda!',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
