/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const FeedbackEntry = IDL.Record({
  'age' : IDL.Nat,
  'feelings' : IDL.Text,
  'country' : IDL.Text,
  'name' : IDL.Text,
  'team' : IDL.Text,
  'timestamp' : Time,
  'thoughts' : IDL.Text,
});
export const SortBy = IDL.Variant({
  'age' : IDL.Null,
  'name' : IDL.Null,
  'timestamp' : IDL.Null,
});
export const QueryFeedbackRequest = IDL.Record({
  'sortBy' : IDL.Opt(SortBy),
  'reverseOrder' : IDL.Bool,
  'limit' : IDL.Nat,
  'filter' : IDL.Opt(
    IDL.Record({
      'minAge' : IDL.Opt(IDL.Nat),
      'maxAge' : IDL.Opt(IDL.Nat),
      'dateRange' : IDL.Opt(
        IDL.Record({ 'startTime' : IDL.Opt(Time), 'endTime' : IDL.Opt(Time) })
      ),
    })
  ),
});

export const idlService = IDL.Service({
  'deleteFeedbackWithPassword' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'getAllFeedback' : IDL.Func([], [IDL.Vec(FeedbackEntry)], ['query']),
  'getCurrentTime' : IDL.Func([], [Time], ['query']),
  'getFeedbackStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalEntries' : IDL.Nat,
          'averageAge' : IDL.Opt(IDL.Nat),
          'uniqueUsers' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getFeedbackSummary' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(FeedbackEntry)],
      ['query'],
    ),
  'isConnected' : IDL.Func([], [IDL.Bool], ['query']),
  'queryFeedback' : IDL.Func(
      [QueryFeedbackRequest],
      [IDL.Vec(FeedbackEntry)],
      [],
    ),
  'searchFeedback' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(FeedbackEntry)],
      ['query'],
    ),
  'submitFeedback' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateFeedbackWithPassword' : IDL.Func(
      [IDL.Nat, FeedbackEntry, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const FeedbackEntry = IDL.Record({
    'age' : IDL.Nat,
    'feelings' : IDL.Text,
    'country' : IDL.Text,
    'name' : IDL.Text,
    'team' : IDL.Text,
    'timestamp' : Time,
    'thoughts' : IDL.Text,
  });
  const SortBy = IDL.Variant({
    'age' : IDL.Null,
    'name' : IDL.Null,
    'timestamp' : IDL.Null,
  });
  const QueryFeedbackRequest = IDL.Record({
    'sortBy' : IDL.Opt(SortBy),
    'reverseOrder' : IDL.Bool,
    'limit' : IDL.Nat,
    'filter' : IDL.Opt(
      IDL.Record({
        'minAge' : IDL.Opt(IDL.Nat),
        'maxAge' : IDL.Opt(IDL.Nat),
        'dateRange' : IDL.Opt(
          IDL.Record({ 'startTime' : IDL.Opt(Time), 'endTime' : IDL.Opt(Time) })
        ),
      })
    ),
  });
  
  return IDL.Service({
    'deleteFeedbackWithPassword' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'getAllFeedback' : IDL.Func([], [IDL.Vec(FeedbackEntry)], ['query']),
    'getCurrentTime' : IDL.Func([], [Time], ['query']),
    'getFeedbackStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalEntries' : IDL.Nat,
            'averageAge' : IDL.Opt(IDL.Nat),
            'uniqueUsers' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getFeedbackSummary' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(FeedbackEntry)],
        ['query'],
      ),
    'isConnected' : IDL.Func([], [IDL.Bool], ['query']),
    'queryFeedback' : IDL.Func(
        [QueryFeedbackRequest],
        [IDL.Vec(FeedbackEntry)],
        [],
      ),
    'searchFeedback' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(FeedbackEntry)],
        ['query'],
      ),
    'submitFeedback' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateFeedbackWithPassword' : IDL.Func(
        [IDL.Nat, FeedbackEntry, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };