/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface FeedbackEntry {
  'age' : bigint,
  'feelings' : string,
  'country' : string,
  'name' : string,
  'team' : string,
  'timestamp' : Time,
  'thoughts' : string,
}
export interface QueryFeedbackRequest {
  'sortBy' : [] | [SortBy],
  'reverseOrder' : boolean,
  'limit' : bigint,
  'filter' : [] | [
    {
      'minAge' : [] | [bigint],
      'maxAge' : [] | [bigint],
      'dateRange' : [] | [
        { 'startTime' : [] | [Time], 'endTime' : [] | [Time] }
      ],
    }
  ],
}
export type SortBy = { 'age' : null } |
  { 'name' : null } |
  { 'timestamp' : null };
export type Time = bigint;
export interface _SERVICE {
  'deleteFeedbackWithPassword' : ActorMethod<[bigint, string], undefined>,
  'getAllFeedback' : ActorMethod<[], Array<FeedbackEntry>>,
  'getCurrentTime' : ActorMethod<[], Time>,
  'getFeedbackStats' : ActorMethod<
    [],
    {
      'totalEntries' : bigint,
      'averageAge' : [] | [bigint],
      'uniqueUsers' : bigint,
    }
  >,
  'getFeedbackSummary' : ActorMethod<[bigint], Array<FeedbackEntry>>,
  'isConnected' : ActorMethod<[], boolean>,
  'queryFeedback' : ActorMethod<[QueryFeedbackRequest], Array<FeedbackEntry>>,
  'searchFeedback' : ActorMethod<[string, bigint], Array<FeedbackEntry>>,
  'submitFeedback' : ActorMethod<
    [string, bigint, string, string, string, string],
    undefined
  >,
  'updateFeedbackWithPassword' : ActorMethod<
    [bigint, FeedbackEntry, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];