/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface QueryFeedbackRequest {
    sortBy?: SortBy;
    reverseOrder: boolean;
    limit: bigint;
    filter?: {
        minAge?: bigint;
        maxAge?: bigint;
        dateRange?: {
            startTime?: Time;
            endTime?: Time;
        };
    };
}
export type Time = bigint;
export interface FeedbackEntry {
    age: bigint;
    feelings: string;
    country: string;
    name: string;
    team: string;
    timestamp: Time;
    thoughts: string;
}
export enum SortBy {
    age = "age",
    name = "name",
    timestamp = "timestamp"
}
export interface backendInterface {
    deleteFeedbackWithPassword(index: bigint, password: string): Promise<void>;
    getAllFeedback(): Promise<Array<FeedbackEntry>>;
    getCurrentTime(): Promise<Time>;
    getFeedbackStats(): Promise<{
        totalEntries: bigint;
        averageAge?: bigint;
        uniqueUsers: bigint;
    }>;
    getFeedbackSummary(limit: bigint): Promise<Array<FeedbackEntry>>;
    isConnected(): Promise<boolean>;
    queryFeedback(request: QueryFeedbackRequest): Promise<Array<FeedbackEntry>>;
    searchFeedback(searchTerm: string, limit: bigint): Promise<Array<FeedbackEntry>>;
    submitFeedback(name: string, age: bigint, country: string, team: string, thoughts: string, feelings: string): Promise<void>;
    updateFeedbackWithPassword(index: bigint, newEntry: FeedbackEntry, password: string): Promise<void>;
}
import type { QueryFeedbackRequest as _QueryFeedbackRequest, SortBy as _SortBy, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async deleteFeedbackWithPassword(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFeedbackWithPassword(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFeedbackWithPassword(arg0, arg1);
            return result;
        }
    }
    async getAllFeedback(): Promise<Array<FeedbackEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFeedback();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFeedback();
            return result;
        }
    }
    async getCurrentTime(): Promise<Time> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentTime();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentTime();
            return result;
        }
    }
    async getFeedbackStats(): Promise<{
        totalEntries: bigint;
        averageAge?: bigint;
        uniqueUsers: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeedbackStats();
                return from_candid_record_n1(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeedbackStats();
            return from_candid_record_n1(this.uploadFile, this.downloadFile, result);
        }
    }
    async getFeedbackSummary(arg0: bigint): Promise<Array<FeedbackEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeedbackSummary(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeedbackSummary(arg0);
            return result;
        }
    }
    async isConnected(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isConnected();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isConnected();
            return result;
        }
    }
    async queryFeedback(arg0: QueryFeedbackRequest): Promise<Array<FeedbackEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.queryFeedback(to_candid_QueryFeedbackRequest_n3(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.queryFeedback(to_candid_QueryFeedbackRequest_n3(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async searchFeedback(arg0: string, arg1: bigint): Promise<Array<FeedbackEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchFeedback(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchFeedback(arg0, arg1);
            return result;
        }
    }
    async submitFeedback(arg0: string, arg1: bigint, arg2: string, arg3: string, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitFeedback(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitFeedback(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updateFeedbackWithPassword(arg0: bigint, arg1: FeedbackEntry, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFeedbackWithPassword(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFeedbackWithPassword(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_opt_n2(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n1(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalEntries: bigint;
    averageAge: [] | [bigint];
    uniqueUsers: bigint;
}): {
    totalEntries: bigint;
    averageAge?: bigint;
    uniqueUsers: bigint;
} {
    return {
        totalEntries: value.totalEntries,
        averageAge: record_opt_to_undefined(from_candid_opt_n2(uploadFile, downloadFile, value.averageAge)),
        uniqueUsers: value.uniqueUsers
    };
}
function to_candid_QueryFeedbackRequest_n3(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QueryFeedbackRequest): _QueryFeedbackRequest {
    return to_candid_record_n4(uploadFile, downloadFile, value);
}
function to_candid_SortBy_n5(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SortBy): _SortBy {
    return to_candid_variant_n6(uploadFile, downloadFile, value);
}
function to_candid_record_n4(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sortBy?: SortBy;
    reverseOrder: boolean;
    limit: bigint;
    filter?: {
        minAge?: bigint;
        maxAge?: bigint;
        dateRange?: {
            startTime?: Time;
            endTime?: Time;
        };
    };
}): {
    sortBy: [] | [_SortBy];
    reverseOrder: boolean;
    limit: bigint;
    filter: [] | [{
            minAge: [] | [bigint];
            maxAge: [] | [bigint];
            dateRange: [] | [{
                    startTime: [] | [_Time];
                    endTime: [] | [_Time];
                }];
        }];
} {
    return {
        sortBy: value.sortBy ? candid_some(to_candid_SortBy_n5(uploadFile, downloadFile, value.sortBy)) : candid_none(),
        reverseOrder: value.reverseOrder,
        limit: value.limit,
        filter: value.filter ? candid_some(to_candid_record_n7(uploadFile, downloadFile, value.filter)) : candid_none()
    };
}
function to_candid_record_n7(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    minAge?: bigint;
    maxAge?: bigint;
    dateRange?: {
        startTime?: Time;
        endTime?: Time;
    };
}): {
    minAge: [] | [bigint];
    maxAge: [] | [bigint];
    dateRange: [] | [{
            startTime: [] | [_Time];
            endTime: [] | [_Time];
        }];
} {
    return {
        minAge: value.minAge ? candid_some(value.minAge) : candid_none(),
        maxAge: value.maxAge ? candid_some(value.maxAge) : candid_none(),
        dateRange: value.dateRange ? candid_some(to_candid_record_n8(uploadFile, downloadFile, value.dateRange)) : candid_none()
    };
}
function to_candid_record_n8(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    startTime?: Time;
    endTime?: Time;
}): {
    startTime: [] | [_Time];
    endTime: [] | [_Time];
} {
    return {
        startTime: value.startTime ? candid_some(value.startTime) : candid_none(),
        endTime: value.endTime ? candid_some(value.endTime) : candid_none()
    };
}
function to_candid_variant_n6(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SortBy): {
    age: null;
} | {
    name: null;
} | {
    timestamp: null;
} {
    return value == SortBy.age ? {
        age: null
    } : value == SortBy.name ? {
        name: null
    } : value == SortBy.timestamp ? {
        timestamp: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, uploadFile, downloadFile, options.processError);
}
